name: Verify Correct Tablet Names

on:
  pull_request:

jobs:
  verify-names:
    runs-on: ubuntu-latest
    name: Verify Tablet Names
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed tablet configs
        id: delta
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: OpenTabletDriver.Configurations/Configurations/**/*.json
          separator: ","

      - name: Check changed configs match TABLETS.md
        if: steps.delta.outputs.any_changed == 'true'
        env:
          TABLETS: TABLETS.md
          CONFIGS: ${{ steps.delta.outputs.all_changed_files }}
        run: |
          IFS=","
          for CONF in $CONFIGS; do
            NAME=$(cat $CONF| jq -r '.Name')
            if ! grep -q "| $NAME " $TABLETS; then
              echo "Failure: '$NAME' was not found in $TABLETS - was it spelt correctly?"
              fi
          done
